### ISSUE TITLE
Changes are still highlighted after committing with magit

### ISSUE THREAD

**Issue by Wilfred** [dgutov/diff-hl#60]
Steps to reproduce:

1. Enable `diff-hl-flydiff-mode`.
2. Modify buffer and save it.
2. Commit changes with magit.
3. Observe that the committed changes are still highlighted until the buffer is further modified.

**Comment by dgutov** [comment]
Does this happen often?

I've just tried it with the latest Magit on a tiny test repo, and the highlighting does go away at step 4, with or without `diff-hl-flydiff-mode` enabled.

To be clear, does step 2 involve saving the buffer after modifying it? I did.

**Comment by dgutov** [comment]
@Wilfred Well?

**Comment by Wilfred** [comment]
Yes, this happens every time for me.

**Comment by dgutov** [comment]
Could you add more details? Does that happen with any Git repository? What's the Magit version? How do you commit (`s`, then `c`)?

**Comment by dgutov** [comment]
With any file, new and already registered?

**Comment by Wilfred** [comment]
Starting from `emacs -q`, I'm doing `eval-buffer` on the following script:

```lisp
(add-to-list 'load-path "/users/is/whughes/.emacs.d/elpa/async-20151103.2309/")
(add-to-list 'load-path "/users/is/whughes/.emacs.d/elpa/dash-20151021.113/")
(add-to-list 'load-path "/users/is/whughes/.emacs.d/elpa/with-editor-20151209.732")
(add-to-list 'load-path "/users/is/whughes/.emacs.d/elpa/magit-popup-20151210.2011")
(add-to-list 'load-path "/users/is/whughes/.emacs.d/elpa/magit-20151209.732/")
(add-to-list 'load-path "/users/is/whughes/.emacs.d/elpa/git-commit-20151111.418")

(add-to-list 'load-path "/users/is/whughes/.emacs.d/elpa/diff-hl-20151120.1715")

(require 'magit)

(require 'diff-hl)
(require 'diff-hl-flydiff)

(diff-hl-mode)
(diff-hl-flydiff-mode)
```

I'm then doing the following

1. Navigate to an existing repo with `C-x C-f` and open README.md in that repo.
2. Add some lines to that file.
3. Save with `C-x C-s`.
4. `M-x magit-status`, stage with `s`, commit with `c c`, write a commit message then `C-c C-c` to create the commit.
5. I can now see the added lines in README.md are still highlighted.

Which code is supposed to run after step 4 to ensure nothing is highlighted after committing?

**Comment by dgutov** [comment]
> Which code is supposed to run after step 4 to ensure nothing is highlighted after committing?

`diff-hl-update` should be called from `magit-not-reverted-hook`.

The backtrace looks like this here:
```
  (closure (t) nil (edebug-enter (quote diff-hl-update) (list) (function (lambda nil (edebug-after (edebug-before 0) 18 (let ((changes ...) (current-line 1)) (edebug-after (edebug-before 3) 4 (diff-hl-remove-overlays)) (edebug-after (edebug-before 5) 17 (save-excursion ...))))))))()
  funcall((closure (t) nil (edebug-enter (quote diff-hl-update) (list) (function (lambda nil (edebug-after (edebug-before 0) 18 (let ((changes ...) (current-line 1)) (edebug-after (edebug-before 3) 4 (diff-hl-remove-overlays)) (edebug-after (edebug-before 5) 17 (save-excursion ...)))))))))
  (if (and auto (or (= diff-hl-flydiff-modified-tick (buffer-modified-tick)) (file-remote-p default-directory) (not (buffer-modified-p)))) nil (funcall old-fun))
  diff-hl-flydiff/update((closure (t) nil (edebug-enter (quote diff-hl-update) (list) (function (lambda nil (edebug-after (edebug-before 0) 18 (let ((changes ...) (current-line 1)) (edebug-after (edebug-before 3) 4 (diff-hl-remove-overlays)) (edebug-after (edebug-before 5) 17 (save-excursion ...)))))))))
  apply(diff-hl-flydiff/update (closure (t) nil (edebug-enter (quote diff-hl-update) (list) (function (lambda nil (edebug-after (edebug-before 0) 18 (let ((changes ...) (current-line 1)) (edebug-after (edebug-before 3) 4 (diff-hl-remove-overlays)) (edebug-after (edebug-before 5) 17 (save-excursion ...)))))))) nil)
  diff-hl-update()
  run-hooks(magit-not-reverted-hook)
  magit-revert-buffer(#<buffer test2>)
  mapcar(magit-revert-buffer (#<buffer test2>))
  magit-revert-buffers-sync((#<buffer test2>) nil)
  magit-revert-buffers()
  magit-refresh()
  magit-process-sentinel(#<process git> "finished\n")
  accept-process-output(nil 0.1)
  with-editor-finish(nil)
```

**Comment by dgutov** [comment]
FWIW, I'm using Magit 20160105.1035, but the aforementioned hook has been added a while ago.

**Comment by dgutov** [comment]
Hmm, there's an around-advice at play here, but it shouldn't have any effect in this case. Do you see `diff-hl-update` (the original definition) get called at the end of committing?

**Comment by dgutov** [comment]
@Wilfred I've pushed a few updates to `diff-hl-flydiff`, but they shouldn't make any difference, as far as this bug is concerned. It seems your problem is that you don't actually enable `diff-hl-mode` in the buffer in question, only `diff-hl-flydiff-mode`. Calling `(diff-hl-mode)` in the init file doesn't do that: it's not a global minor mode. See the usage instructions in `diff-hl.el`, at the top.

**Comment by dgutov** [comment]
`diff-hl-flydiff-update` is now changed to avoid this kind of confusion.

Thanks for bringing this to my attention.

**Comment by manuel-uberti** [comment]
This is still happening with `diff-hl-20160114.1559` and `magit-20160114.1814`.

**Comment by dgutov** [comment]
@manuel-uberti What's your config?

**Comment by manuel-uberti** [comment]
Here it is:
```
(use-package diff-hl                    ; Show changes in fringe
  :ensure t
  :defer 10
  :init
  (progn
    ;; Highlight changes to the current file in the fringe
    (global-diff-hl-mode)
    ;; Highlight changed files in the fringe of Dired
    (add-hook 'dired-mode-hook 'diff-hl-dired-mode)
    ;; Fall back to the display margin, if the fringe is unavailable
    (unless (display-graphic-p)
      (diff-hl-margin-mode))))
```

**Comment by dgutov** [comment]
@manuel-uberti This is caused by a recent Magit change. I've just installed the latest version, and also see the problem.

**Comment by manuel-uberti** [comment]
Ok, thank you for the time spent investigating this issue.

**Comment by manuel-uberti** [comment]
Any news on this one?

**Comment by dgutov** [comment]
None.

You should follow the linked Magit issue.

**Comment by manuel-uberti** [comment]
Ok, thanks.

**Comment by dgutov** [comment]
See the new addition to the README.
